//! C code generator for dsPIC33 and PIC24 PPS pin configuration.
//!
//! Generates C and header outputs for PPS-remappable and fixed-function
//! pin assignments. Outputs MISRA C:2012 compliant C99 code.
//!
//! Generation is intentionally phase-ordered:
//! 1. optional oscillator/fuse pragmas
//! 2. PPS configuration
//! 3. ANSEL/TRIS port setup
//! 4. optional analog peripheral enables
//! 5. `system_init()` calling those routines in hardware-safe order
//!
//! Detailed emitters for PPS, GPIO/analog setup, and CLC now live in focused
//! submodules so this file can remain the top-level phase orchestrator.

use std::collections::HashMap;

use crate::codegen::generate_clc::append_configure_clc_function;
pub use crate::codegen::generate_clc::ClcModuleConfig;
use crate::codegen::generate_ports::{
    append_configure_analog_function, append_configure_ports_function, collect_opamp_numbers,
};
use crate::codegen::generate_pps::append_configure_pps_function;
use crate::codegen::generate_single_file::merge_generated_files;
use crate::codegen::generate_support::{
    align_comments, extend_aligned_sections, filter_fuse_pragmas_for_oscillator,
    push_section_comment, sanitize_signal_name,
};
pub use crate::codegen::generate_types::{
    generated_file_names, GenerateOutputOptions, GeneratedFileNames, PinAssignment, PinConfig,
    DEFAULT_OUTPUT_BASENAME,
};
use crate::codegen::oscillator::{generate_osc_code_for_device, OscConfig};
use crate::parser::edc_parser::DeviceData;

pub fn generate_c_files(
    device: &DeviceData,
    config: &PinConfig,
    package: Option<&str>,
    signal_names: Option<&HashMap<u32, String>>,
    osc_config: Option<&OscConfig>,
    fuse_pragmas: Option<&str>,
    clc_modules: Option<&HashMap<u32, ClcModuleConfig>>,
) -> HashMap<String, String> {
    generate_c_files_named(
        device,
        config,
        signal_names,
        osc_config,
        fuse_pragmas,
        clc_modules,
        GenerateOutputOptions {
            package,
            output_basename: DEFAULT_OUTPUT_BASENAME,
        },
    )
}

pub fn generate_c_files_named(
    device: &DeviceData,
    config: &PinConfig,
    signal_names: Option<&HashMap<u32, String>>,
    osc_config: Option<&OscConfig>,
    fuse_pragmas: Option<&str>,
    clc_modules: Option<&HashMap<u32, ClcModuleConfig>>,
    output: GenerateOutputOptions<'_>,
) -> HashMap<String, String> {
    let filenames = generated_file_names(output.output_basename);
    let pinout = device.get_pinout(output.package);
    let resolved = device.resolve_pins(output.package);
    let pin_by_pos: HashMap<u32, _> = resolved.iter().map(|p| (p.position, p)).collect();
    let empty_sig: HashMap<u32, String> = HashMap::new();
    let sig = signal_names.unwrap_or(&empty_sig);

    // Emit helper functions only when a matching feature is actually used.
    let has_pps = config
        .assignments
        .iter()
        .any(|assign| !assign.fixed && (assign.direction == "in" || assign.direction == "out"));
    let opamp_nums = collect_opamp_numbers(&config.assignments);
    let has_opamp = !opamp_nums.is_empty();
    let has_clc = clc_modules.is_some_and(|m| !m.is_empty());

    let (osc_pragmas, osc_init) = if let Some(osc) = osc_config {
        generate_osc_code_for_device(&device.part_number, osc)
    } else {
        (String::new(), String::new())
    };
    let filtered_fuse_pragmas = fuse_pragmas
        .and_then(|text| filter_fuse_pragmas_for_oscillator(text, &device.part_number, osc_config));

    // =========================================================================
    // Generate the configured header output.
    // =========================================================================
    let mut h_lines = Vec::new();
    h_lines.push("/**".into());
    h_lines.push(format!(" * @file   {}", filenames.header));
    h_lines.push(format!(
        " * @brief  Pin configuration header for {} ({})",
        device.part_number, pinout.package
    ));
    h_lines.push(" *".into());
    h_lines.push(" * @note   Generated by pickle. MISRA C:2012 compliant.".into());
    h_lines.push(" */".into());
    h_lines.push(String::new());
    h_lines.push("#ifndef PIN_CONFIG_H".into());
    h_lines.push("#define PIN_CONFIG_H".into());
    h_lines.push(String::new());
    h_lines.push("#include <xc.h>".into());
    h_lines.push(String::new());

    // Signal name defines
    if !sig.is_empty() {
        push_section_comment(
            &mut h_lines,
            "Signal name aliases",
            &["Maps user-defined signal names to PORT/LAT/TRIS bit-fields."],
        );
        for assign in &config.assignments {
            if let Some(name) = sig.get(&assign.pin_position) {
                if name.is_empty() {
                    continue;
                }
                if let Some(pin) = pin_by_pos.get(&assign.pin_position) {
                    if let (Some(port), Some(bit)) = (&pin.port, pin.port_bit) {
                        let safe_name = sanitize_signal_name(name);
                        h_lines.push(format!(
                            "#define {}_PORT  (PORT{}bits.R{}{})",
                            safe_name, port, port, bit
                        ));
                        h_lines.push(format!(
                            "#define {}_LAT   (LAT{}bits.LAT{}{})",
                            safe_name, port, port, bit
                        ));
                        h_lines.push(format!(
                            "#define {}_TRIS  (TRIS{}bits.TRIS{}{})",
                            safe_name, port, port, bit
                        ));
                    }
                }
            }
        }
        h_lines.push(String::new());
    }

    // Function prototypes
    h_lines.push("/* Function prototypes */".into());
    if !osc_init.is_empty() {
        h_lines.push("void configure_oscillator(void);".into());
    }
    if has_pps {
        h_lines.push("void configure_pps(void);".into());
    }
    h_lines.push("void configure_ports(void);".into());
    if has_opamp {
        h_lines.push("void configure_analog(void);".into());
    }
    if has_clc {
        h_lines.push("void configure_clc(void);".into());
    }
    h_lines.push("void system_init(void);".into());
    h_lines.push(String::new());
    h_lines.push("#endif /* PIN_CONFIG_H */".into());
    h_lines.push(String::new());

    // =========================================================================
    // Generate the configured C output.
    // =========================================================================
    let mut c_lines: Vec<String> = Vec::new();

    c_lines.push("/**".into());
    c_lines.push(format!(" * @file   {}", filenames.source));
    c_lines.push(format!(
        " * @brief  Pin configuration for {} ({})",
        device.part_number, pinout.package
    ));
    c_lines.push(" *".into());
    c_lines.push(" * Configures PPS remappable pin mappings, analog/digital selection,".into());
    c_lines.push(" * and pin direction (TRIS) registers.".into());
    c_lines.push(" *".into());
    c_lines.push(" * @note   Generated by pickle. MISRA C:2012 compliant.".into());
    c_lines.push(" */".into());
    c_lines.push(String::new());
    c_lines.push(format!("#include \"{}\"", filenames.header));
    c_lines.push(String::new());

    // Oscillator pragmas are emitted first because Microchip expects config
    // pragmas near the top of the translation unit.
    if !osc_pragmas.is_empty() {
        let aligned = align_comments(
            &osc_pragmas
                .lines()
                .map(|s| s.to_string())
                .collect::<Vec<_>>(),
        );
        c_lines.extend(aligned);
        c_lines.push(String::new());
    }

    // Align fuse pragmas section-by-section so unrelated pragma groups do not
    // try to share one huge comment column.
    if let Some(fuse_text) = filtered_fuse_pragmas.as_deref() {
        if !fuse_text.is_empty() {
            extend_aligned_sections(&mut c_lines, fuse_text);
            c_lines.push(String::new());
        }
    }

    // Oscillator init function
    if !osc_init.is_empty() {
        c_lines.push(osc_init.clone());
    }

    append_configure_pps_function(
        &mut c_lines,
        &config.assignments,
        &resolved,
        &device.pps_input_mappings,
        &device.pps_output_mappings,
        sig,
    );
    append_configure_ports_function(
        &mut c_lines,
        device,
        &config.assignments,
        &config.digital_pins,
        &resolved,
    );
    append_configure_analog_function(&mut c_lines, device, &opamp_nums);

    // configure_clc() — CLC module initialization
    if let Some(clc_mods) = clc_modules.filter(|mods| !mods.is_empty()) {
        append_configure_clc_function(&mut c_lines, clc_mods, &device.part_number);
    }

    // system_init()
    push_section_comment(
        &mut c_lines,
        "system_init",
        &[
            "",
            "Master initialization function. Calls all configuration routines in the",
            "correct order: oscillator first (clock must be stable), then PPS (requires",
            "unlock/lock), then port direction/analog, then peripheral enables.",
        ],
    );
    c_lines.push("void system_init(void)".into());
    c_lines.push("{".into());
    if !osc_init.is_empty() {
        c_lines.push("    configure_oscillator();".into());
    }
    if has_pps {
        c_lines.push("    configure_pps();".into());
    }
    c_lines.push("    configure_ports();".into());
    if has_opamp {
        c_lines.push("    configure_analog();".into());
    }
    if has_clc {
        c_lines.push("    configure_clc();".into());
    }
    c_lines.push("}".into());
    c_lines.push(String::new());

    c_lines.push(format!("/* End of {} */", filenames.source));
    c_lines.push(String::new());

    let mut result = HashMap::new();
    result.insert(filenames.header, h_lines.join("\n"));
    result.insert(filenames.source, c_lines.join("\n"));
    result
}

/// Generate a single self-contained C file (backward-compatible for compile-check).
pub fn generate_c_code(
    device: &DeviceData,
    config: &PinConfig,
    package: Option<&str>,
    signal_names: Option<&HashMap<u32, String>>,
    osc_config: Option<&OscConfig>,
    fuse_pragmas: Option<&str>,
) -> String {
    generate_c_code_named(
        device,
        config,
        package,
        signal_names,
        osc_config,
        fuse_pragmas,
        DEFAULT_OUTPUT_BASENAME,
    )
}

pub fn generate_c_code_named(
    device: &DeviceData,
    config: &PinConfig,
    package: Option<&str>,
    signal_names: Option<&HashMap<u32, String>>,
    osc_config: Option<&OscConfig>,
    fuse_pragmas: Option<&str>,
    output_basename: &str,
) -> String {
    let filenames = generated_file_names(output_basename);
    let files = generate_c_files_named(
        device,
        config,
        signal_names,
        osc_config,
        fuse_pragmas,
        None,
        GenerateOutputOptions {
            package,
            output_basename,
        },
    );
    let h_content = &files[&filenames.header];
    let c_content = &files[&filenames.source];
    merge_generated_files(&filenames.header, h_content, c_content)
}

#[cfg(test)]
mod tests;
